### ISSUE TITLE
Looks different on gh-pages

### ISSUE THREAD

**Issue by sevagh** [lucachr/pelican-mg#4]
Hello,

I used this theme in my Pelican enabled blog (https://github.com/sevagh/blog)

When I run it locally, it looks like your screenshots (green banners, etc.), but when I do "make github" (which uses ghp-import if I'm not mistaken), the result looks different: http://sevagh.github.io/blog/

**Comment by lucachr** [comment]
Hi, thank you for reporting this issue. I've changed the urls for css and js from relative to absolute ones, so now the theme should work as expected.
